### ISSUE TITLE
Add 2.0.8

### ISSUE THREAD

**Issue by fanatid** [ExodusMovement/docker-parity#1]
https://github.com/paritytech/parity-ethereum/releases/tag/v2.0.7

**Comment by fanatid** [comment]
Already 2.0.8 -- they fixed bugs in 2.0.7 )

**Comment by roccomuso** [comment]
Available also 2.1.3-beta.

**Comment by fanatid** [comment]
No, let's ignore beta...

**Comment by fanatid** [comment]
Thank you
